

server:
  port: 3081
spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
      - id: doctor
        uri: http://localhost:3001/
        predicates:
        - Path=/doctor/**
      - id: patient
        uri: http://localhost:3002/
        predicates:
        - Path=/patient/**
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:3000/eureka
  registerWithEureka:
       - true
  fetchRegistry:
       - true
